# Bank Churn Analysis

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
raw_data = pd.read_csv('./Datset/Customer-Churn-Records.csv')
df = raw_data.copy()

df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Complain,Satisfaction Score,Card Type,Point Earned
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,1,2,DIAMOND,464
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,1,3,DIAMOND,456
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,1,3,DIAMOND,377
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,0,5,GOLD,350
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,0,5,GOLD,425

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   RowNumber           10000 non-null  int64
 1   CustomerId          10000 non-null  int64
 2   Surname             10000 non-null  object
 3   CreditScore         10000 non-null  int64
 4   Geography           10000 non-null  object
 5   Gender              10000 non-null  object
 6   Age                 10000 non-null  int64
 7   Tenure              10000 non-null  int64
 8   Balance             10000 non-null  float64
 9   NumOfProducts       10000 non-null  int64
 10  HasCrCard           10000 non-null  int64
 11  IsActiveMember      10000 non-null  int64
 12  EstimatedSalary     10000 non-null  float64
 13  Exited              10000 non-null  int64
 14  Complain            10000 non-null  int64
 15  Satisfaction Score  10000 non-null  int64
 16  Card Type           10000 non-null  object
 17  Point Earned        10000 non-null  int64
dtypes: float64(2), int64(12), object(4)
memory usage: 1.4+ MB

## Drop column

In [13]:
drop_feature = ['Surname', 'RowNumber', 'CustomerId']
df = df.drop(drop_feature, axis=1)

In [15]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Complain,Satisfaction Score,Card Type,Point Earned
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1,1,2,DIAMOND,464
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,1,3,DIAMOND,456
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,1,3,DIAMOND,377
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0,0,5,GOLD,350
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,0,5,GOLD,425

## แบ่ง Train/Test set

In [19]:
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTEN, SMOTE
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder

In [21]:
X = df.drop('Exited', axis=1)
y = df['Exited']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.3, random_state=42)

## One-Hot Encoding

In [24]:
# One-Hot Encoding -> Geography, Gender, Card Type
categorical_col = df.select_dtypes(include='object').columns
numerical_col = df.select_dtypes(exclude='object').columns

In [26]:
categorical_col

Index(['Geography', 'Gender', 'Card Type'], dtype='object')

In [28]:
ordinal_encoder = OrdinalEncoder()
oh_encoder = OneHotEncoder(sparse_output=False).set_output(transform='pandas')

for col in categorical_col:
        d_train = oh_encoder.fit_transform(X_train[[col]])
        X_train = pd.concat( [X_train.drop(col, axis=1), d_train.astype('int64') ], axis=1)
    
        d_test = oh_encoder.transform(X_test[[col]])
        X_test = pd.concat( [X_test.drop(col, axis=1), d_test.astype('int64') ], axis=1)

In [30]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7000 entries, 9069 to 7270
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   CreditScore         7000 non-null   int64
 1   Age                 7000 non-null   int64
 2   Tenure              7000 non-null   int64
 3   Balance             7000 non-null   float64
 4   NumOfProducts       7000 non-null   int64
 5   HasCrCard           7000 non-null   int64
 6   IsActiveMember      7000 non-null   int64
 7   EstimatedSalary     7000 non-null   float64
 8   Complain            7000 non-null   int64
 9   Satisfaction Score  7000 non-null   int64
 10  Point Earned        7000 non-null   int64
 11  Geography_France    7000 non-null   int64
 12  Geography_Germany   7000 non-null   int64
 13  Geography_Spain     7000 non-null   int64
 14  Gender_Female       7000 non-null   int64
 15  Gender_Male         7000 non-null   int64
 16  Card Type_DIAMOND   7000 non-null   int64
 17  Card Type_GOLD      7000 non-null   int64
 18  Card Type_PLATINUM  7000 non-null   int64
 19  Card Type_SILVER    7000 non-null   int64
dtypes: float64(2), int64(18)
memory usage: 1.1 MB

In [32]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3000 entries, 6252 to 4705
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   CreditScore         3000 non-null   int64
 1   Age                 3000 non-null   int64
 2   Tenure              3000 non-null   int64
 3   Balance             3000 non-null   float64
 4   NumOfProducts       3000 non-null   int64
 5   HasCrCard           3000 non-null   int64
 6   IsActiveMember      3000 non-null   int64
 7   EstimatedSalary     3000 non-null   float64
 8   Complain            3000 non-null   int64
 9   Satisfaction Score  3000 non-null   int64
 10  Point Earned        3000 non-null   int64
 11  Geography_France    3000 non-null   int64
 12  Geography_Germany   3000 non-null   int64
 13  Geography_Spain     3000 non-null   int64
 14  Gender_Female       3000 non-null   int64
 15  Gender_Male         3000 non-null   int64
 16  Card Type_DIAMOND   3000 non-null   int64
 17  Card Type_GOLD      3000 non-null   int64
 18  Card Type_PLATINUM  3000 non-null   int64
 19  Card Type_SILVER    3000 non-null   int64
dtypes: float64(2), int64(18)
memory usage: 492.2 KB

## Feature Scaling

In [35]:
from sklearn.preprocessing import MinMaxScaler

In [37]:
X_train.columns

Index(['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Complain', 'Satisfaction Score',
       'Point Earned', 'Geography_France', 'Geography_Germany',
       'Geography_Spain', 'Gender_Female', 'Gender_Male', 'Card Type_DIAMOND',
       'Card Type_GOLD', 'Card Type_PLATINUM', 'Card Type_SILVER'],
      dtype='object')

In [41]:
scaling_feature = ['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
                   'IsActiveMember', 'EstimatedSalary', 'Complain', 'Satisfaction Score',
                   'Point Earned']


scaler = MinMaxScaler()
# Scaling Train set
X_train[scaling_feature] = scaler.fit_transform(X_train[scaling_feature])
# Scaling Test set
X_test[scaling_feature] = scaler.transform(X_test[scaling_feature])

In [43]:
X_train.describe()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Complain,Satisfaction Score,Point Earned,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male,Card Type_DIAMOND,Card Type_GOLD,Card Type_PLATINUM,Card Type_SILVER
count,7000.000000,7000.000000,7000.000000,7000.000000,7000.000000,7000.000000,7000.000000,7000.000000,7000.000000,7000.000000,7000.000000,7000.000000,7000.000000,7000.000000,7000.000000,7000.000000,7000.000000,7000.000000,7000.000000,7000.000000
mean,0.604318,0.282429,0.498671,0.304498,0.174762,0.705571,0.514857,0.503979,0.208286,0.502643,0.528892,0.500857,0.248857,0.250286,0.453286,0.546714,0.250714,0.248714,0.254000,0.246571
std,0.192465,0.141981,0.288390,0.249187,0.193473,0.455818,0.499815,0.288471,0.406111,0.351822,0.267750,0.500035,0.432382,0.433208,0.497849,0.497849,0.433455,0.432299,0.435329,0.431046
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.472000,0.189189,0.275000,0.000000,0.000000,0.000000,0.000000,0.258217,0.000000,0.250000,0.297192,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.606000,0.256757,0.500000,0.384551,0.000000,1.000000,1.000000,0.504116,0.000000,0.500000,0.525687,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
75%,0.738500,0.351351,0.700000,0.509540,0.333333,1.000000,1.000000,0.751698,0.000000,0.750000,0.757467,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [45]:
X_test.describe()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Complain,Satisfaction Score,Point Earned,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male,Card Type_DIAMOND,Card Type_GOLD,Card Type_PLATINUM,Card Type_SILVER
count,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000
mean,0.593451,0.283423,0.507367,0.305666,0.181333,0.705333,0.515667,0.491713,0.195333,0.505333,0.532207,0.502667,0.255667,0.241667,0.456667,0.543333,0.250667,0.253667,0.239000,0.256667
std,0.195077,0.141154,0.291097,0.247588,0.194797,0.455969,0.499838,0.285837,0.396523,0.350731,0.274954,0.500076,0.436308,0.428165,0.498202,0.498202,0.433469,0.435182,0.426544,0.436867
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.000393,0.000000,0.000000,-0.052569,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.460000,0.189189,0.300000,0.000000,0.000000,0.000000,0.000000,0.246086,0.000000,0.250000,0.292712,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.598000,0.263514,0.500000,0.392311,0.333333,1.000000,1.000000,0.488401,0.000000,0.500000,0.529869,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
75%,0.726000,0.351351,0.800000,0.506656,0.333333,1.000000,1.000000,0.731895,0.000000,0.750000,0.772999,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000
max,1.000000,1.000000,1.000000,0.861345,1.000000,1.000000,1.000000,1.000109,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

## Oversampling : SMOTEN / SMOTE

In [48]:
smoten = SMOTEN(random_state=42)
smote = SMOTE(random_state=42)

num_train_col = ['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 
                 'HasCrCard', 'IsActiveMember', 'EstimatedSalary', 'Complain', 
                 'Satisfaction Score', 'Point Earned']
cat_train_col = ['Geography_France','Geography_Germany', 'Geography_Spain', 
                 'Gender_Female', 'Gender_Male',  'Card Type_DIAMOND', 'Card Type_GOLD', 
                 'Card Type_PLATINUM', 'Card Type_SILVER']

dummy_y_train = y_train.copy()

# Categorical Data
cat_X_train_sample, y_train_sample = smoten.fit_resample(X_train[cat_train_col], y_train)
# Numerical Data
num_X_train_sample, dummy_y_train_sample = smote.fit_resample(X_train[num_train_col], dummy_y_train)

In [50]:
# รวมข้อมูลที่ oversampling โดย SMOTEN และ SMOTE
X_train_sample = pd.concat( [num_X_train_sample, cat_X_train_sample], axis=1)
X_train_sample

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Complain,Satisfaction Score,Point Earned,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male,Card Type_DIAMOND,Card Type_GOLD,Card Type_PLATINUM,Card Type_SILVER
0,0.538000,0.189189,0.400000,0.699113,0.333333,1.0,1.0,0.864027,1.0,0.000000,0.649940,0,0,1,1,0,1,0,0,0
1,0.586000,0.216216,0.700000,0.639407,0.000000,0.0,1.0,0.942778,0.0,0.500000,0.768220,0,1,0,1,0,0,1,0,0
2,0.422000,0.202703,0.600000,0.000000,0.333333,0.0,0.0,0.868470,0.0,0.500000,0.068100,1,0,0,0,1,1,0,0,0
3,0.536000,0.310811,0.800000,0.150271,0.000000,1.0,1.0,0.979011,0.0,1.000000,0.540024,0,1,0,0,1,0,1,0,0
4,0.728000,0.256757,0.900000,0.591742,0.333333,0.0,1.0,0.756406,0.0,0.500000,0.923536,1,0,0,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11087,0.730223,0.436435,0.100000,0.429036,0.122082,0.0,0.0,0.446406,1.0,0.591561,0.153950,1,0,0,1,0,0,0,0,1
11088,0.726547,0.098170,0.228101,0.000000,0.000000,1.0,0.0,0.170965,1.0,0.535127,0.357023,0,0,1,0,1,0,1,0,0
11089,0.674685,0.402685,0.144295,0.443870,0.000000,1.0,1.0,0.558461,1.0,1.000000,0.365503,1,0,0,1,0,1,0,0,0
11090,0.497508,0.277142,0.856144,0.000000,0.666667,0.0,1.0,0.448469,1.0,0.609640,0.388114,0,0,1,0,1,0,1,0,0
11091,0.752187,0.366139,0.200000,0.448801,0.000000,1.0,0.0,0.557254,1.0,0.787739,0.145984,0,0,1,1,0,0,1,0,0

In [52]:
X_train_sample.describe()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Complain,Satisfaction Score,Point Earned,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male,Card Type_DIAMOND,Card Type_GOLD,Card Type_PLATINUM,Card Type_SILVER
count,11092.000000,11092.000000,11092.000000,11092.000000,11092.000000,11092.000000,11092.000000,11092.000000,11092.000000,11092.000000,11092.000000,11092.000000,11092.000000,11092.000000,11092.000000,11092.000000,11092.000000,11092.000000,11092.000000,11092.000000
mean,0.599007,0.312114,0.494075,0.325021,0.159586,0.703660,0.458078,0.505298,0.500055,0.497456,0.527091,0.467003,0.298774,0.234223,0.493419,0.506581,0.264605,0.241886,0.251082,0.242427
std,0.186647,0.137230,0.284984,0.240435,0.214216,0.456663,0.498262,0.282572,0.499968,0.348363,0.260503,0.498933,0.457741,0.423531,0.499979,0.499979,0.441143,0.428245,0.433655,0.428571
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.469317,0.216216,0.241650,0.000000,0.000000,0.000000,0.000000,0.262837,0.000000,0.250000,0.299881,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.600000,0.297297,0.500000,0.409402,0.000000,1.000000,0.000000,0.504700,0.614896,0.500000,0.529271,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
75%,0.729923,0.391923,0.720941,0.512055,0.333333,1.000000,1.000000,0.752349,1.000000,0.750000,0.744375,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [54]:
y_train_sample

0        1
1        0
2        0
3        0
4        0
        ..
11087    1
11088    1
11089    1
11090    1
11091    1
Name: Exited, Length: 11092, dtype: int64

## Feature Engineering

In [57]:
X_train_sample.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11092 entries, 0 to 11091
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   CreditScore         11092 non-null  float64
 1   Age                 11092 non-null  float64
 2   Tenure              11092 non-null  float64
 3   Balance             11092 non-null  float64
 4   NumOfProducts       11092 non-null  float64
 5   HasCrCard           11092 non-null  float64
 6   IsActiveMember      11092 non-null  float64
 7   EstimatedSalary     11092 non-null  float64
 8   Complain            11092 non-null  float64
 9   Satisfaction Score  11092 non-null  float64
 10  Point Earned        11092 non-null  float64
 11  Geography_France    11092 non-null  int64
 12  Geography_Germany   11092 non-null  int64
 13  Geography_Spain     11092 non-null  int64
 14  Gender_Female       11092 non-null  int64
 15  Gender_Male         11092 non-null  int64
 16  Card Type_DIAMOND   11092 non-null  int64
 17  Card Type_GOLD      11092 non-null  int64
 18  Card Type_PLATINUM  11092 non-null  int64
 19  Card Type_SILVER    11092 non-null  int64
dtypes: float64(11), int64(9)
memory usage: 1.7 MB

### Risk Score

#### Train Set

In [59]:
X_train_sample['Risk Score'] = ( (X_train_sample['Age'] * .3)
                                + (X_train_sample['Balance'] * .1)
                                + (X_train_sample['IsActiveMember'] * .4)
                                + (X_train_sample['NumOfProducts'] * .3) * 100)

In [61]:
X_train_sample['Risk Score'].describe()

count    11092.000000
mean         5.096959
std          6.435702
min          0.008108
25%          0.164926
50%          0.553869
75%         10.165745
max         30.626769
Name: Risk Score, dtype: float64

#### Test Set

In [64]:
X_test['Risk Score'] = ( (X_test['Age'] * .3)
                                + (X_test['Balance'] * .1)
                                + (X_test['IsActiveMember'] * .4)
                                + (X_test['NumOfProducts'] * .3) * 100)

In [66]:
X_test['Risk Score'].describe()

count    3000.000000
mean        5.761860
std         5.834131
min         0.004054
25%         0.460514
50%        10.020270
75%        10.448649
max        30.603491
Name: Risk Score, dtype: float64

### Loyalty Score

#### Train Set

In [70]:
X_train_sample['Loyalty Score'] = ((X_train_sample['Tenure']*0.2)
                 + (X_train_sample['IsActiveMember']*0.5)
                 + (X_train_sample['NumOfProducts']*0.3))*100

In [72]:
X_train_sample['Loyalty Score']

0        68.000000
1        64.000000
2        22.000000
3        66.000000
4        78.000000
           ...
11087     5.662459
11088     4.562029
11089    52.885902
11090    87.122877
11091     4.000000
Name: Loyalty Score, Length: 11092, dtype: float64

#### Test Set

In [75]:
X_test['Loyalty Score'] = ((X_test['Tenure']*0.2)
                 + (X_test['IsActiveMember']*0.5)
                 + (X_test['NumOfProducts']*0.3))*100

In [77]:
X_test['Loyalty Score'].describe()

count    3000.000000
mean       41.370667
std        25.856839
min         0.000000
25%        16.000000
50%        52.000000
75%        66.000000
max       100.000000
Name: Loyalty Score, dtype: float64

### Feature Scaling (Risk Score, Loyalty Score)

In [80]:
new_scaler = MinMaxScaler()

X_train_sample['Risk Score'] = new_scaler.fit_transform(X_train_sample[['Risk Score']])
X_test['Risk Score'] = new_scaler.transform(X_test[['Risk Score']])


X_train_sample['Loyalty Score'] = new_scaler.fit_transform(X_train_sample[['Loyalty Score']])
X_test['Loyalty Score'] = new_scaler.transform(X_test[['Loyalty Score']])

## รวบข้อมูล X, y เป็น train set ก้อนเดียว

In [82]:
train_data = pd.concat( [X_train_sample, y_train_sample ], axis=1)
train_data

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Complain,Satisfaction Score,...,Geography_Spain,Gender_Female,Gender_Male,Card Type_DIAMOND,Card Type_GOLD,Card Type_PLATINUM,Card Type_SILVER,Risk Score,Loyalty Score,Exited
0,0.538000,0.189189,0.400000,0.699113,0.333333,1.0,1.0,0.864027,1.0,0.000000,...,1,1,0,1,0,0,0,0.343534,0.680000,1
1,0.586000,0.216216,0.700000,0.639407,0.000000,0.0,1.0,0.942778,0.0,0.500000,...,0,1,0,0,1,0,0,0.017006,0.640000,0
2,0.422000,0.202703,0.600000,0.000000,0.333333,0.0,0.0,0.868470,0.0,0.500000,...,0,0,1,1,0,0,0,0.328319,0.220000,0
3,0.536000,0.310811,0.800000,0.150271,0.000000,1.0,1.0,0.979011,0.0,1.000000,...,0,0,1,0,1,0,0,0.016335,0.660000,0
4,0.728000,0.256757,0.900000,0.591742,0.333333,0.0,1.0,0.756406,0.0,0.500000,...,0,0,1,0,0,0,1,0.343846,0.780000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11087,0.730223,0.436435,0.100000,0.429036,0.122082,0.0,0.0,0.446406,1.0,0.591561,...,0,1,0,0,0,0,1,0.125028,0.056625,1
11088,0.726547,0.098170,0.228101,0.000000,0.000000,1.0,0.0,0.170965,1.0,0.535127,...,1,0,1,0,1,0,0,0.000697,0.045620,1
11089,0.674685,0.402685,0.144295,0.443870,0.000000,1.0,1.0,0.558461,1.0,1.000000,...,0,1,0,1,0,0,0,0.018194,0.528859,1
11090,0.497508,0.277142,0.856144,0.000000,0.666667,0.0,1.0,0.448469,1.0,0.609640,...,1,0,1,0,1,0,0,0.668711,0.871229,1
11091,0.752187,0.366139,0.200000,0.448801,0.000000,1.0,0.0,0.557254,1.0,0.787739,...,1,1,0,0,1,0,0,0.004788,0.040000,1

## ตัด Outlier จาก train set

In [86]:
suspect_col = ['CreditScore', 'Age', 'NumOfProducts', 'Risk Score']

### IQR

In [91]:
for col in suspect_col:
    q1 = train_data[col].quantile(.25)
    q3 = train_data[col].quantile(.75)
    IQR = q3 - q1
    lower_b = q1 - (IQR * 1.75)
    upper_b = q3 + (IQR * 1.75)
    print(f'{col}:')
    print(f'upper_bond = {upper_b}:')
    print(f'lower_bond = {lower_b}:')
    print('-'*40)

CreditScore:
upper_bond = 1.1859843787626552:
lower_bond = 0.013255546993334144:
----------------------------------------
Age:
upper_bond = 0.6994087547266024:
lower_bond = -0.09126994465402949:
----------------------------------------
NumOfProducts:
upper_bond = 0.9166666666666665:
lower_bond = -0.5833333333333333:
----------------------------------------
Risk Score:
upper_bond = 0.9033402740704235:
lower_bond = -0.566472025058751:
----------------------------------------

### กรอง Outlier

In [94]:
creditscore_condition = ((train_data['CreditScore'] >= 0.0172729685651849) & (train_data['CreditScore'] <= 1.1802808381857912))
age_condition = ((train_data['Age'] >= -0.09680261499374149) & (train_data['Age'] <= 0.7081029509747212))
numofproducts_condition = ((train_data['NumOfProducts'] >= -0.5833333333333333) & (train_data['NumOfProducts'] <= 0.9166666666666665))
risk_score_condition = ( (train_data['Risk Score'] >= -17.371413079051315) & (train_data['Risk Score'] <= 27.72695659329569) )

In [100]:
train_data = train_data[
    creditscore_condition & age_condition & numofproducts_condition & risk_score_condition
]

C:\Users\USER\AppData\Local\Temp\ipykernel_17420\2566773181.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  train_data = train_data[

In [104]:
train_data

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Complain,Satisfaction Score,...,Geography_Spain,Gender_Female,Gender_Male,Card Type_DIAMOND,Card Type_GOLD,Card Type_PLATINUM,Card Type_SILVER,Risk Score,Loyalty Score,Exited
0,0.538000,0.189189,0.400000,0.699113,0.333333,1.0,1.0,0.864027,1.0,0.000000,...,1,1,0,1,0,0,0,0.343534,0.680000,1
1,0.586000,0.216216,0.700000,0.639407,0.000000,0.0,1.0,0.942778,0.0,0.500000,...,0,1,0,0,1,0,0,0.017006,0.640000,0
2,0.422000,0.202703,0.600000,0.000000,0.333333,0.0,0.0,0.868470,0.0,0.500000,...,0,0,1,1,0,0,0,0.328319,0.220000,0
3,0.536000,0.310811,0.800000,0.150271,0.000000,1.0,1.0,0.979011,0.0,1.000000,...,0,0,1,0,1,0,0,0.016335,0.660000,0
4,0.728000,0.256757,0.900000,0.591742,0.333333,0.0,1.0,0.756406,0.0,0.500000,...,0,0,1,0,0,0,1,0.343846,0.780000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11087,0.730223,0.436435,0.100000,0.429036,0.122082,0.0,0.0,0.446406,1.0,0.591561,...,0,1,0,0,0,0,1,0.125028,0.056625,1
11088,0.726547,0.098170,0.228101,0.000000,0.000000,1.0,0.0,0.170965,1.0,0.535127,...,1,0,1,0,1,0,0,0.000697,0.045620,1
11089,0.674685,0.402685,0.144295,0.443870,0.000000,1.0,1.0,0.558461,1.0,1.000000,...,0,1,0,1,0,0,0,0.018194,0.528859,1
11090,0.497508,0.277142,0.856144,0.000000,0.666667,0.0,1.0,0.448469,1.0,0.609640,...,1,0,1,0,1,0,0,0.668711,0.871229,1
11091,0.752187,0.366139,0.200000,0.448801,0.000000,1.0,0.0,0.557254,1.0,0.787739,...,1,1,0,0,1,0,0,0.004788,0.040000,1

In [106]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10896 entries, 0 to 11091
Data columns (total 23 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   CreditScore         10896 non-null  float64
 1   Age                 10896 non-null  float64
 2   Tenure              10896 non-null  float64
 3   Balance             10896 non-null  float64
 4   NumOfProducts       10896 non-null  float64
 5   HasCrCard           10896 non-null  float64
 6   IsActiveMember      10896 non-null  float64
 7   EstimatedSalary     10896 non-null  float64
 8   Complain            10896 non-null  float64
 9   Satisfaction Score  10896 non-null  float64
 10  Point Earned        10896 non-null  float64
 11  Geography_France    10896 non-null  int64
 12  Geography_Germany   10896 non-null  int64
 13  Geography_Spain     10896 non-null  int64
 14  Gender_Female       10896 non-null  int64
 15  Gender_Male         10896 non-null  int64
 16  Card Type_DIAMOND   10896 non-null  int64
 17  Card Type_GOLD      10896 non-null  int64
 18  Card Type_PLATINUM  10896 non-null  int64
 19  Card Type_SILVER    10896 non-null  int64
 20  Risk Score          10896 non-null  float64
 21  Loyalty Score       10896 non-null  float64
 22  Exited              10896 non-null  int64
dtypes: float64(13), int64(10)
memory usage: 2.0 MB

In [108]:
train_data['Exited'].value_counts()

Exited
0    5458
1    5438
Name: count, dtype: int64

## ตรวจสอบข้อมูลครั้งสุดท้าย

In [111]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10896 entries, 0 to 11091
Data columns (total 23 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   CreditScore         10896 non-null  float64
 1   Age                 10896 non-null  float64
 2   Tenure              10896 non-null  float64
 3   Balance             10896 non-null  float64
 4   NumOfProducts       10896 non-null  float64
 5   HasCrCard           10896 non-null  float64
 6   IsActiveMember      10896 non-null  float64
 7   EstimatedSalary     10896 non-null  float64
 8   Complain            10896 non-null  float64
 9   Satisfaction Score  10896 non-null  float64
 10  Point Earned        10896 non-null  float64
 11  Geography_France    10896 non-null  int64
 12  Geography_Germany   10896 non-null  int64
 13  Geography_Spain     10896 non-null  int64
 14  Gender_Female       10896 non-null  int64
 15  Gender_Male         10896 non-null  int64
 16  Card Type_DIAMOND   10896 non-null  int64
 17  Card Type_GOLD      10896 non-null  int64
 18  Card Type_PLATINUM  10896 non-null  int64
 19  Card Type_SILVER    10896 non-null  int64
 20  Risk Score          10896 non-null  float64
 21  Loyalty Score       10896 non-null  float64
 22  Exited              10896 non-null  int64
dtypes: float64(13), int64(10)
memory usage: 2.0 MB

In [113]:
for col in cat_train_col:
    print(train_data.groupby(col)[col].sum())
    print('-'*40)

Geography_France
0       0
1    5089
Name: Geography_France, dtype: int64
----------------------------------------
Geography_Germany
0       0
1    3249
Name: Geography_Germany, dtype: int64
----------------------------------------
Geography_Spain
0       0
1    2558
Name: Geography_Spain, dtype: int64
----------------------------------------
Gender_Female
0       0
1    5359
Name: Gender_Female, dtype: int64
----------------------------------------
Gender_Male
0       0
1    5537
Name: Gender_Male, dtype: int64
----------------------------------------
Card Type_DIAMOND
0       0
1    2882
Name: Card Type_DIAMOND, dtype: int64
----------------------------------------
Card Type_GOLD
0       0
1    2625
Name: Card Type_GOLD, dtype: int64
----------------------------------------
Card Type_PLATINUM
0       0
1    2738
Name: Card Type_PLATINUM, dtype: int64
----------------------------------------
Card Type_SILVER
0       0
1    2651
Name: Card Type_SILVER, dtype: int64
----------------------------------------

## Export Dataset

In [116]:
# Train set
train_data.to_csv('./Datset/train_ver_1.csv')

In [118]:
# Test set
test_data = pd.concat( [X_test, y_test], axis=1)
test_data.to_csv('./Datset/test_ver_1.csv')

In [ ]:
train_data.columns

Index(['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Complain', 'Satisfaction Score',
       'Point Earned', 'Geography_France', 'Geography_Germany',
       'Geography_Spain', 'Gender_Female', 'Gender_Male', 'Card Type_DIAMOND',
       'Card Type_GOLD', 'Card Type_PLATINUM', 'Card Type_SILVER',
       'Risk Score', 'Loyalty Score', 'Exited'],
      dtype='object')

In [ ]:
test_data.columns

Index(['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Complain', 'Satisfaction Score',
       'Point Earned', 'Geography_France', 'Geography_Germany',
       'Geography_Spain', 'Gender_Female', 'Gender_Male', 'Card Type_DIAMOND',
       'Card Type_GOLD', 'Card Type_PLATINUM', 'Card Type_SILVER',
       'Risk Score', 'Loyalty Score', 'Exited'],
      dtype='object')

In [ ]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10896 entries, 0 to 11091
Data columns (total 23 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   CreditScore         10896 non-null  float64
 1   Age                 10896 non-null  float64
 2   Tenure              10896 non-null  float64
 3   Balance             10896 non-null  float64
 4   NumOfProducts       10896 non-null  float64
 5   HasCrCard           10896 non-null  float64
 6   IsActiveMember      10896 non-null  float64
 7   EstimatedSalary     10896 non-null  float64
 8   Complain            10896 non-null  float64
 9   Satisfaction Score  10896 non-null  float64
 10  Point Earned        10896 non-null  float64
 11  Geography_France    10896 non-null  int64
 12  Geography_Germany   10896 non-null  int64
 13  Geography_Spain     10896 non-null  int64
 14  Gender_Female       10896 non-null  int64
 15  Gender_Male         10896 non-null  int64
 16  Card Type_DIAMOND   10896 non-null  int64
 17  Card Type_GOLD      10896 non-null  int64
 18  Card Type_PLATINUM  10896 non-null  int64
 19  Card Type_SILVER    10896 non-null  int64
 20  Risk Score          10896 non-null  float64
 21  Loyalty Score       10896 non-null  float64
 22  Exited              10896 non-null  int64
dtypes: float64(13), int64(10)
memory usage: 2.0 MB

In [ ]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3000 entries, 6252 to 4705
Data columns (total 23 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   CreditScore         3000 non-null   float64
 1   Age                 3000 non-null   float64
 2   Tenure              3000 non-null   float64
 3   Balance             3000 non-null   float64
 4   NumOfProducts       3000 non-null   float64
 5   HasCrCard           3000 non-null   float64
 6   IsActiveMember      3000 non-null   float64
 7   EstimatedSalary     3000 non-null   float64
 8   Complain            3000 non-null   float64
 9   Satisfaction Score  3000 non-null   float64
 10  Point Earned        3000 non-null   float64
 11  Geography_France    3000 non-null   int64
 12  Geography_Germany   3000 non-null   int64
 13  Geography_Spain     3000 non-null   int64
 14  Gender_Female       3000 non-null   int64
 15  Gender_Male         3000 non-null   int64
 16  Card Type_DIAMOND   3000 non-null   int64
 17  Card Type_GOLD      3000 non-null   int64
 18  Card Type_PLATINUM  3000 non-null   int64
 19  Card Type_SILVER    3000 non-null   int64
 20  Risk Score          3000 non-null   float64
 21  Loyalty Score       3000 non-null   float64
 22  Exited              3000 non-null   int64
dtypes: float64(13), int64(10)
memory usage: 562.5 KB