In [68]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [69]:
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTEN, SMOTE
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder

In [70]:
raw_data = pd.read_csv('./Datset/Customer-Churn-Records.csv')
df = raw_data.copy()
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Complain,Satisfaction Score,Card Type,Point Earned
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,1,2,DIAMOND,464
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,1,3,DIAMOND,456
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,1,3,DIAMOND,377
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,0,5,GOLD,350
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,0,5,GOLD,425

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   RowNumber           10000 non-null  int64
 1   CustomerId          10000 non-null  int64
 2   Surname             10000 non-null  object
 3   CreditScore         10000 non-null  int64
 4   Geography           10000 non-null  object
 5   Gender              10000 non-null  object
 6   Age                 10000 non-null  int64
 7   Tenure              10000 non-null  int64
 8   Balance             10000 non-null  float64
 9   NumOfProducts       10000 non-null  int64
 10  HasCrCard           10000 non-null  int64
 11  IsActiveMember      10000 non-null  int64
 12  EstimatedSalary     10000 non-null  float64
 13  Exited              10000 non-null  int64
 14  Complain            10000 non-null  int64
 15  Satisfaction Score  10000 non-null  int64
 16  Card Type           10000 non-null  object
 17  Point Earned        10000 non-null  int64
dtypes: float64(2), int64(12), object(4)
memory usage: 1.4+ MB

## Drop column ที่ไม่จำเป็น

In [73]:
drop_feature = ['CustomerId','Surname', 'RowNumber']
df = df.drop(drop_feature, axis=1)

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   CreditScore         10000 non-null  int64
 1   Geography           10000 non-null  object
 2   Gender              10000 non-null  object
 3   Age                 10000 non-null  int64
 4   Tenure              10000 non-null  int64
 5   Balance             10000 non-null  float64
 6   NumOfProducts       10000 non-null  int64
 7   HasCrCard           10000 non-null  int64
 8   IsActiveMember      10000 non-null  int64
 9   EstimatedSalary     10000 non-null  float64
 10  Exited              10000 non-null  int64
 11  Complain            10000 non-null  int64
 12  Satisfaction Score  10000 non-null  int64
 13  Card Type           10000 non-null  object
 14  Point Earned        10000 non-null  int64
dtypes: float64(2), int64(10), object(3)
memory usage: 1.1+ MB

## แบ่ง Train/Test set

In [76]:
X = df.drop('Exited', axis=1)
y = df['Exited']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=42)

## One-Hot Encoding

In [78]:
categorical_col = df.select_dtypes(include='object').columns
numerical_col = df.select_dtypes(exclude='object').columns

print(categorical_col)
print('-'*80)
print(numerical_col)

Index(['Geography', 'Gender', 'Card Type'], dtype='object')
--------------------------------------------------------------------------------
Index(['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited', 'Complain',
       'Satisfaction Score', 'Point Earned'],
      dtype='object')

In [79]:
or_encoder = OrdinalEncoder()
oh_encoder = OneHotEncoder(sparse_output=False).set_output(transform='pandas')

for col in categorical_col:
        d_train = oh_encoder.fit_transform(X_train[[col]])
        X_train = pd.concat([X_train.drop(col, axis=1), d_train.astype('int64')], axis=1)
        d_test = oh_encoder.transform(X_test[[col]])
        X_test = pd.concat([X_test.drop(col, axis=1), d_test.astype('int64')], axis=1)

In [80]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8000 entries, 9254 to 7270
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   CreditScore         8000 non-null   int64
 1   Age                 8000 non-null   int64
 2   Tenure              8000 non-null   int64
 3   Balance             8000 non-null   float64
 4   NumOfProducts       8000 non-null   int64
 5   HasCrCard           8000 non-null   int64
 6   IsActiveMember      8000 non-null   int64
 7   EstimatedSalary     8000 non-null   float64
 8   Complain            8000 non-null   int64
 9   Satisfaction Score  8000 non-null   int64
 10  Point Earned        8000 non-null   int64
 11  Geography_France    8000 non-null   int64
 12  Geography_Germany   8000 non-null   int64
 13  Geography_Spain     8000 non-null   int64
 14  Gender_Female       8000 non-null   int64
 15  Gender_Male         8000 non-null   int64
 16  Card Type_DIAMOND   8000 non-null   int64
 17  Card Type_GOLD      8000 non-null   int64
 18  Card Type_PLATINUM  8000 non-null   int64
 19  Card Type_SILVER    8000 non-null   int64
dtypes: float64(2), int64(18)
memory usage: 1.3 MB

In [81]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2000 entries, 6252 to 6929
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   CreditScore         2000 non-null   int64
 1   Age                 2000 non-null   int64
 2   Tenure              2000 non-null   int64
 3   Balance             2000 non-null   float64
 4   NumOfProducts       2000 non-null   int64
 5   HasCrCard           2000 non-null   int64
 6   IsActiveMember      2000 non-null   int64
 7   EstimatedSalary     2000 non-null   float64
 8   Complain            2000 non-null   int64
 9   Satisfaction Score  2000 non-null   int64
 10  Point Earned        2000 non-null   int64
 11  Geography_France    2000 non-null   int64
 12  Geography_Germany   2000 non-null   int64
 13  Geography_Spain     2000 non-null   int64
 14  Gender_Female       2000 non-null   int64
 15  Gender_Male         2000 non-null   int64
 16  Card Type_DIAMOND   2000 non-null   int64
 17  Card Type_GOLD      2000 non-null   int64
 18  Card Type_PLATINUM  2000 non-null   int64
 19  Card Type_SILVER    2000 non-null   int64
dtypes: float64(2), int64(18)
memory usage: 328.1 KB

## Feature Scaling

In [83]:
from sklearn.preprocessing import MinMaxScaler

In [84]:
X_train.columns

Index(['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Complain', 'Satisfaction Score',
       'Point Earned', 'Geography_France', 'Geography_Germany',
       'Geography_Spain', 'Gender_Female', 'Gender_Male', 'Card Type_DIAMOND',
       'Card Type_GOLD', 'Card Type_PLATINUM', 'Card Type_SILVER'],
      dtype='object')

In [85]:
scaling_feature = ['CreditScore', 'Age', 'Tenure', 'Balance',
                   'NumOfProducts', 'HasCrCard', 'IsActiveMember',
                   'EstimatedSalary', 'Complain', 'Satisfaction Score',
                   'Point Earned']

In [86]:
scaler = MinMaxScaler()

# Scaling Train set
X_train[scaling_feature] = scaler.fit_transform(X_train[scaling_feature])
# Scaling Test set
X_test[scaling_feature] = scaler.transform(X_test[scaling_feature])

In [87]:
X_train

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Complain,Satisfaction Score,Point Earned,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male,Card Type_DIAMOND,Card Type_GOLD,Card Type_PLATINUM,Card Type_SILVER
9254,0.672,0.189189,0.6,0.000000,0.333333,1.0,1.0,0.895550,0.0,0.25,0.414576,1,0,0,0,1,1,0,0,0
1561,0.564,0.324324,0.4,0.476786,0.333333,1.0,1.0,0.980029,0.0,0.75,0.951016,0,1,0,0,1,0,0,1,0
1670,0.418,0.081081,0.3,0.457317,0.000000,1.0,0.0,0.429261,1.0,0.75,0.195938,0,0,1,0,1,0,0,0,1
6087,0.422,0.121622,0.9,0.540606,0.000000,1.0,0.0,0.765408,1.0,0.25,0.482676,1,0,0,1,0,0,0,0,1
6669,0.334,0.513514,0.9,0.566554,0.000000,0.0,0.0,0.197107,1.0,0.50,0.673835,1,0,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5734,0.836,0.486486,0.8,0.277853,0.000000,1.0,1.0,0.346662,0.0,0.50,0.485066,1,0,0,0,1,0,0,0,1
5191,0.664,0.540541,0.1,0.000000,0.000000,1.0,1.0,0.003084,0.0,0.75,0.652330,1,0,0,1,0,0,0,1,0
5390,0.770,0.270270,0.1,0.000000,0.666667,0.0,0.0,0.460925,1.0,1.00,0.615293,1,0,0,1,0,0,0,0,1
860,0.634,0.337838,0.8,0.758186,0.000000,1.0,0.0,0.487381,1.0,0.50,0.617682,1,0,0,0,1,1,0,0,0
7270,0.694,0.445946,0.1,0.589523,0.000000,1.0,1.0,0.267615,0.0,0.75,0.568698,0,1,0,0,1,1,0,0,0

In [88]:
X_test

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Complain,Satisfaction Score,Point Earned,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male,Card Type_DIAMOND,Card Type_GOLD,Card Type_PLATINUM,Card Type_SILVER
6252,0.492,0.189189,0.3,0.385452,0.333333,0.0,0.0,0.208616,0.0,0.00,0.652330,0,1,0,0,1,0,1,0,0
4684,0.546,0.337838,0.1,0.000000,0.333333,1.0,1.0,0.731883,0.0,0.25,0.412186,1,0,0,0,1,0,0,0,1
1731,0.502,0.351351,0.4,0.000000,0.333333,1.0,0.0,0.292531,0.0,0.00,0.140980,0,0,1,1,0,0,1,0,0
4742,0.312,0.554054,0.8,0.474902,0.333333,1.0,1.0,0.853458,0.0,0.25,0.974910,0,1,0,0,1,0,0,0,1
4521,0.420,0.121622,0.7,0.498194,0.000000,1.0,1.0,0.573241,0.0,1.00,0.351254,0,0,1,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6412,0.504,0.472973,0.5,0.391668,0.000000,0.0,1.0,0.224875,1.0,1.00,0.776583,0,1,0,1,0,0,0,1,0
8285,0.518,0.094595,1.0,0.000000,0.000000,0.0,1.0,0.549353,0.0,0.25,0.584229,1,0,0,0,1,0,0,1,0
7853,0.760,0.391892,0.7,0.000000,0.000000,1.0,0.0,0.166515,1.0,0.25,0.407407,1,0,0,1,0,0,0,1,0
1095,0.684,0.148649,0.4,0.000000,0.000000,1.0,0.0,0.383558,1.0,0.50,0.624851,1,0,0,0,1,0,0,1,0
6929,0.556,0.283784,0.1,0.459713,0.000000,1.0,1.0,0.538242,1.0,0.75,0.864994,0,1,0,0,1,0,0,0,1

## ทำ Oversampling : SMOTEN / SMOTE

In [90]:
smoten = SMOTEN(random_state=42)
smote = SMOTE(random_state=42)

num_train_col = ['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts',
                 'HasCrCard', 'IsActiveMember', 'EstimatedSalary', 'Complain',
                 'Satisfaction Score', 'Point Earned']
cat_train_col = ['Geography_France','Geography_Germany', 'Geography_Spain',
                 'Gender_Female', 'Gender_Male',  'Card Type_DIAMOND', 'Card Type_GOLD',
                 'Card Type_PLATINUM', 'Card Type_SILVER']

dummy_y_train = y_train.copy()

# Categorical Data
cat_X_train_sample, y_train_sample = smoten.fit_resample(X_train[cat_train_col], y_train)

# Numerical Data
num_X_train_sample, dummy_y_train_sample = smote.fit_resample(X_train[num_train_col], dummy_y_train)

## Feature Engineering

#### Risk Score Train Set

In [93]:
X_train_sample['Risk Score'] = ( (X_train_sample['Age'] * .3) 
                                + (X_train_sample['Balance'] * .1) 
                                + (X_train_sample['IsActiveMember'] * .4) 
                                + (X_train_sample['NumOfProducts'] * .3) * 100)

NameError: name 'X_train_sample' is not defined

#### Risk Score Test Set

In [ ]:
X_test['Risk Score'] = ( (X_test['Age'] * .3) 
                                + (X_test['Balance'] * .1) 
                                + (X_test['IsActiveMember'] * .4) 
                                + (X_test['NumOfProducts'] * .3) * 100)

In [ ]:
X_test['Risk Score'].describe()

#### Loyalty Score Train Set

In [ ]:
X_train_sample['Loyalty Score'] = ((X_train_sample['Tenure']*0.2) 
                 + (X_train_sample['IsActiveMember']*0.5) 
                 + (X_train_sample['NumOfProducts']*0.3))*100